name: Backend Deploy to Ubuntu Server

on:
  push:
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set unique tag
      run: echo "TAG=backend-$(date +%s)" >> $GITHUB_ENV

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/Docker-test-frontback/backend
          docker ps -a --filter "name=backend-" -q | xargs -r docker rm -f
          docker images "backend-*" -q | xargs -r docker rmi -f
          docker build -t ${{ env.TAG }} .
          docker run -d --name ${{ env.TAG }} -p 5000:5000 ${{ env.TAG }}
